# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-09 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='occupation',
            field=models.CharField(max_length=20),
        ),
    ]
